---
title: "04-exercices-ARDl-cointégration"
author: "Romain CAPLIEZ"
format: html
editor: visual
---

# Exercice 1 : L'Hypothèse de Fisher et la Cointégration

**Données :** `intdef` du package `wooldridge`.

**Objectif :** Tester la relation de long terme entre le taux d'intérêt des bons du trésor à 3 mois (`i3`) et le taux d'inflation (`inf`). Selon l'effet Fisher, une augmentation de l'inflation devrait se traduire par une augmentation équivalente des taux d'intérêt nominaux à long terme (coefficient de 1).

## Question 0

Charger le setup de l'analyse

## Question 1

Importer les données `intdef`. Créer un nouvel objet TS contenant les variables `i3` et `inf`. Représenter graphiquement les deux séries sur le même graphique. Semblent-elles évoluer ensemble ?

## Question 2

Réaliser les tests de stationnarité sur les deux variables. Sont-elles intégrées du même ordre ? Peut-on réaliser la procédure d'Engle-Granger pour la cointégration ? Si oui tester la cointégration entre ces deux variables avec cette procédure. Estimer le modèle à correction d'erreur lié. Que peut-on en conclure ?

## Question 3

Estimer un modèle ARDL pour expliquer `i3` par `inf`. Quel sont les ordres choisi ? Pourquoi ?

## Question 4

Réaliser le test des bornes (Bounds Test) sur le modèle estimé. Peut-on conclure à l'existence d'une relation de cointégration entre les taux d'intérêt et l'inflation au seuil de 5% ? Au seuil de 1% ?

## Question 5

Si la cointégration est avérée, estimer les coefficients de long terme. Le coefficient associé à l'inflation est-il statistiquement différent de 1 ? L'hypothèse de Fisher est-elle validée sur cette période ?

## Question 6

Estimer le modèle à correction d'erreur (ECM) associé. Quelle est la vitesse d'ajustement vers l'équilibre de long terme ? Commentez son signe et sa significativité.

## Question 7

Représenter l'équation de long-terme de `i3` et la comparer aux données réelles. Que pouvez-vous en dire ?

## Question 8

Le modèle satisfait-il les hypothèses des MCO ? Si non comment pourriez-vous corriger cela ?

# Exercice 2 : La courbe de Phillips

Le trésor américain vous demande d'utiliser les données `phillips` du package `woolridge` afin de tester l'existence de la courbe de Phillips, c'est à dire l'existence d'une relation négative entre l'inflation et le chômage. Définissez une stratégie et une modélisation pour tester cette relation. Cette relation existe-t-elle à court- et long-terme ? Comment se situe l'inflation réelle par rapport à son niveau de long-terme ? Que pourriez-vous proposer au trésor américain pour améliorer l'analyse ?

# Exercice 3

```{r}
source(here::here("02-codes", "utils", "setup.R"))

data("fertil3")

df_ts <-
  fertil3  |> 
  mutate(
    year = lubridate::make_date(year)
  ) |> 
  timetk::tk_ts(
    select = c(gfr, pe, pill, ww2),
    start = min(fertil3$year),
    frequency = 1
  )

df_ts |> 
  timetk::tk_tbl(rename_index = "year") |> 
  pivot_longer(
    cols = c(gfr, pe),
    names_to = "nom",
    values_to = "valeur"
  ) |> 
  ggplot(aes(x = year, y = valeur)) +
  geom_line() +
  facet_wrap("nom", scales=  "free")

if (rlang::is_installed("dobby")) {
  purrr::map2_dfr(
    list(fertil3$gfr, fertil3$pe), 
    c("gfr", "pe"), 
    \(serie, name) dobby::adf_test_auto(
      serie, name, 
      lags = 20, 
      message = FALSE, 
      return_res = TRUE
    )
  )
} else {
  print("Le package 'dobby' n'est pas installé.")
}

df <- 
  df_ts |> 
  timetk::tk_tbl(rename_index = "year") |> 
  mutate(
    across(
      .cols = c(gfr, pe),
      .fns = \(x) log(x),
      .names = "log_{.col}"
    ),
    across(
      .cols = c(log_gfr, log_pe),
      .fns = \(x) x - lag(x),
      .names = "diff_{.col}"
    ),
    across(
      .cols = !year,
      .fns = \(x) if_else(is.infinite(x), NA, x)
    ),
    year = lubridate::make_date(year)
  ) |>
  drop_na() 
  
df_ts_extended <- 
  df |> 
  timetk::tk_ts(
    select = !year,
    start = year(min(df$year)),
    frequency = 1
  )
  
model_selection <- 
  auto_ardl(
    log_gfr ~ log_pe | ww2 + pill, 
    data = df_ts_extended, 
    max_order = 5,
    selection = "BIC"
  )

model_selection$top_orders

model <- model_selection$best_model

summary(model)

uecm_model <- ARDL::uecm(model)

summary(uecm_model)

bounds_f_test(uecm_model, case = 2)

bounds_t_test(uecm_model, case = 3)

multipliers(model)

multipliers(model, type = "sr")
```
